import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Login from './Login'
import Hub from './Hub'
import { ReactElement } from 'react';

const Home: NextPage = ( ) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='dark'>
        <Hub/>
      </main>
    </div>
  )
}

export default Home
